public  class Player {

    public void playing(){
        String playerName1 = 'AbCDe';
        String playerName2 = 'DE';
        String playerName3 = 'fGHJk';
        String playerName4 = 'KLmNoP';
        String playerName5 = 'QRSTUV';


        system.debug('playerName1 is '+playerName1+'\n'+
        'playerName2 is '+playerName2+'\n'+
        'playerName3 is '+playerName3+'\n'+
        'playerName4 is '+playerName4+'\n'+
        'playerName5 is '+playerName5);

        system.debug('playerName1 length is '+playerName1.length()+'\n'+
        'playerName2 length is '+playerName2.length()+'\n'+
        'playerName3 length is '+playerName3.length()+'\n'+
        'playerName4 length is '+playerName4.length()+'\n'+
        'playerName5 length is '+playerName5.length());

        system.debug('playerName1 in capital is '+playerName1.toUpperCase()+'\n'+
        'playerName4 in capital is '+playerName4.toUpperCase());

        



    }
    
    
}